from src.document import Documenter
import argparse
import subprocess
import os

CODE_EXTENSIONS = {
    # General programming languages
    '.c', '.cpp', '.cxx', '.cc', '.h', '.hpp', '.hxx', '.inl', '.tcc',  # C/C++ family
    '.java', '.class', '.jar',  # Java
    '.py',  # Python
    '.rb',  # Ruby
    '.js', '.jsx', '.mjs',  # JavaScript
    '.ts', '.tsx', '.d.ts',  # TypeScript
    '.go',  # Go
    '.php',  # PHP
    '.swift',  # Swift
    '.kt', '.kts',  # Kotlin
    '.r', '.rmd',  # R
    '.lua',  # Lua
    '.pl', '.pm',  # Perl
    '.sh', '.bash', '.zsh', '.fish',  # Shell scripts
    '.html', '.htm', '.xhtml',  # HTML
    '.css',  # CSS
    '.less', '.scss', '.sass',  # CSS preprocessors
    '.json',  # JSON
    '.xml',  # XML
    '.yml', '.yaml',  # YAML
    '.sql',  # SQL
    '.vhdl', '.vhd',  # VHDL
    '.asm', '.s', '.asm32',  # Assembly languages
    '.m', '.mm',  # Objective-C and Objective-C++
    '.scala',  # Scala
    '.clj', '.cljs',  # Clojure
    '.hs',  # Haskell
    '.elm',  # Elm
    '.nim',  # Nim
    '.d',  # D programming language
    '.vala',  # Vala
    '.racket',  # Racket (Scheme-based language)
    '.f90', '.f95', '.f03', '.f08',  # Fortran
    '.objc', '.objcpp',  # Objective-C++ and Objective-C
    '.tsv',  # Tab-separated values
    '.xsd',  # XML Schema Definition
    '.csv',  # Comma-separated values
    '.csv',  # Comma-separated values
    '.cabal',  # Haskell's Cabal build system
    '.el',  # Emacs Lisp
    '.sml',  # Standard ML
    '.coffee',  # CoffeeScript
    '.pug',  # Pug (formerly Jade)
    '.twig',  # Twig
    '.handlebars',  # Handlebars
    '.rpy',  # Ren'Py (Python-based)
    '.jl',  # Julia
    '.sh',  # Shell scripts
    '.awk',  # AWK script
    '.dart',  # Dart
    '.hbs',  # Handlebars template
    '.groovy',  # Groovy
    '.v',  # Verilog (hardware description language)
    '.fs', '.fsx',  # F# (F Sharp)
    '.gdb',  # GDB (Debugger scripts)
    '.ps1',  # PowerShell script
    '.scss',  # Sass (CSS preprocessor)
    '.ts',  # TypeScript
}

TOGETHER_MODELS = {"zero-one-ai/Yi-34B-Chat",
"deepseek-ai/deepseek-llm-67b-chat",
"google/gemma-2b-it",
"Gryphe/MythoMax-L2-13b-Lite",
"meta-llama/Llama-3-70b-chat-hf",	
"meta-llama/Meta-Llama-3-8B-Instruct-Turbo"}
OPENAI_MODELS = {"gpt-4o-mini-2024-07-18",
                 "o3-mini-2025-01-31",
                 "gpt-4o-2024-08-06"}
ANTHROPIC_MODELS = {"claude-3-7-sonnet-latest",
                    "claude-3-5-haiku-20241022",
                    "claude-3-5-sonnet-latest",
                    "claude-3-opus-latest"}
def main():
  parser = argparse.ArgumentParser(description="Parse command line arguments")
  parser.add_argument('root', type=str, help='The top level directory to process')
  parser.add_argument('--hidden', action='store_true', help='Include hidden files')
  parser.add_argument('--all', action='store_true', help='Include all files')
  parser.add_argument('--filewise', action='store_true', help="generate a md file for each code file")

  parser.add_argument('--langs', type=str, help='Languages to include (e.g., .js .py)', default="")
  parser.add_argument('--github', type=str, help='link to a github repo to document', default="")
  parser.add_argument('--api_key', type=str, help='your claude api key  ', default="")
  parser.add_argument('--provider', type=str, help='your provider: claude, openai, or together', default="")
  parser.add_argument('--model', type=str, help="the model you want to use", default="")

  # Parse the arguments
  args = parser.parse_args()


  if args.github != "":
     print('here')
     subprocess.run(['git', 'clone', args.github])


  file, hidden, all_, api_key, provider, model = args.root, args.hidden, args.all, args.api_key, args.provider, args.model
  if args.langs:
      langs_list = set(args.langs.split())
  else:
      langs_list = CODE_EXTENSIONS
  
  if provider=='together':
     if model not in TOGETHER_MODELS:
        raise ValueError("""Invalid model. Currently supported together AI models are zero-one-ai/Yi-34B-Chat,
deepseek-ai/deepseek-llm-67b-chat,
google/gemma-2b-it,
Gryphe/MythoMax-L2-13b-Lite,
meta-llama/Llama-3-70b-chat-hf,	and
meta-llama/Meta-Llama-3-8B-Instruct-Turbo""")
  elif provider=='claude':
     if model not in ANTHROPIC_MODELS:
        raise ValueError("Invalid model. Currently supported claude models are: claude-3-7-sonnet-latest ",
                    "claude-3-5-haiku-20241022 ",
                    "claude-3-5-sonnet-latest ", 'and ',
                    "claude-3-opus-latest ")



  documenter = Documenter(file, api_key=api_key, provider=provider, model=model)
  documenter.document(file, 0, hidden, all_, extensions=langs_list)
  documenter.summarize()

  if args.github:
     os.chdir(file)
     for file_ in documenter.files:
      to_add = os.path.basename(file_)+'.md'
      subprocess.run(['git', 'add', to_add])
     subprocess.run(['git', 'commit', '-m', '"Documenation generated by Claude :p"'])
     subprocess.run(['git', 'push'])
     os.chdir('..')
     print(os.getcwd())
     print(file)
     subprocess.run(['rm', '-rf', file])

if __name__ == "__main__":
   main()

